language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=2.4.33
  matrix:
    - TAG=2.4.33 APACHE_VER=2.4.33

script:
  - cd ./"${APACHE_VER:0:3}"/alpine
  - travis_retry make

after_success:
  - . "${TRAVIS_BUILD_DIR}/travis_release"
