language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=2.1.1
  matrix:
    - APACHE_VER=2.4.34 ALPINE_VER=3.7 TAGS=2.4.34,2.4,2,latest

script:
  - cd ./"${APACHE_VER:0:3}"/alpine
  - travis_retry make

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
