language: bash

services:
  - docker

env:
    - APACHE_VER=2.4.34 TAGS=2.4.34,latest

script:
  - cd ./"${APACHE_VER:0:3}"/alpine
  - travis_retry make

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
